env:
  TERM: alacritty

window:
  decorations: none
  dynamic_padding: true
  opacity: 0.95
  padding:
    x: 5
    y: 5

scrolling:
  history: 1000
  multiplier: 3

font:
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Regular

  bold:
    family: JetBrainsMono Nerd Font Mono
    style: Bold

  italic:
    family: JetBrainsMono Nerd Font Mono
    style: Italic

  bold_italic:
    family: JetBrainsMono Nerd Font Mono
    style: SemiBold Italic

  size: 14.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: true

  selection:
    sematic_escape_chars: ",│`|:\"' ()[]{}<>\t"
    save_to_clipboard: true
    live_config_reload: true

cursor:
  style: Block
  blinking: on
  blink_interval: 500
  blink_timeout: 2
  thickness: 0.2

shell:
  program: /bin/zsh
  args:
    - --login

# NORD
colors:
  primary:
    background: '#2e3440'
    foreground: '#d8dee9'
    dim_foreground: '#a5abb6'
  cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  vi_mode_cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  selection:
    text: CellForeground
    background: '#4c566a'
  search:
    matches:
      foreground: CellBackground
      background: '#88c0d0'
    bar:
      background: '#434c5e'
      foreground: '#d8dee9'
  normal:
    black: '#3b4252'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#88c0d0'
    white: '#e5e9f0'
  bright:
    black: '#4c566a'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#8fbcbb'
    white: '#eceff4'
  dim:
    black: '#373e4d'
    red: '#94545d'
    green: '#809575'
    yellow: '#b29e75'
    blue: '#68809a'
    magenta: '#8c738c'
    cyan: '#6d96a5'
    white: '#aeb3bb'
