#!/bin/sh

# prompt
set promptfmt "[\033[32;1m%u\033[0m]:[\033[34;1m%d\033[0m\033[1m%f\033[0m]"

# script
set previewer ~/.config/lf/preview_kitty_img.sh
set cleaner ~/.config/lf/clean_kitty_img.sh

# opts
set hidden true
set drawbox true
set icons true
set ignorecase true
set relativenumber true
set sortby 'natural'; set info size
set scrolloff 10

# custom function
cmd open ${{
    case $(file --mime-type -Lb $f) in
        text/*) $EDITOR $fx;;
        video/*) "mpv" $fx ;;
        image/*)
        if [ "$TERM" = "tmux-256color" ]; then
            open -a qview $fx
        else
            false
        fi
        ;;
        application/pdf) "zathura" $fx ;;
        *) for f in $fx; do setsid $OPENER $f > /dev/null 2> /dev/null & done;;
    esac
}}

cmd bulk-rename ${{
    old="$(mktemp)"
    new="$(mktemp)"
    if [ -n "$fs" ]; then
        fs="$(basename -a $fs)"
    else
        fs="$(ls)"
    fi
    printf '%s\n' "$fs" >"$old"
    printf '%s\n' "$fs" >"$new"
    $EDITOR "$new"
    [ "$(wc -l < "$new")" -ne "$(wc -l < "$old")" ] && exit
    paste "$old" "$new" | while IFS= read -r names; do
        src="$(printf '%s' "$names" | cut -f1)"
        dst="$(printf '%s' "$names" | cut -f2)"
        if [ "$src" = "$dst" ] || [ -e "$dst" ]; then
            continue
        fi
        mv -- "$src" "$dst"
    done
    rm -- "$old" "$new"
    lf -remote "send $id unselect"
}}

cmd mvdir %set -f; printf " Directory Name: "; read ans; mkdir -- "$ans"; mv -- $fx "$ans"
cmd mkdir %set -f; printf " Directory Name: "; read ans; mkdir -p $ans
cmd setwallpaper %set -f; printf " Desktop Number: "; read ans; desktop-image-switcher $f $ans
cmd mkfile %set -f; printf " File Name: "; read ans; touch $ans
cmd trash %set -f; printf " Are you sure, delete [y/n] "; read ans; [ $ans = "y" ] && trash $f

# clear key for recieve multiple keymap
map g
map m
map r
map e
map c

# chain function into key
map rs rename
map rb bulk-rename
map mf mkfile
map md mkdir
map mv mvdir

# basic key
map . set hidden!
map D trash
map p paste
map x cut
map y copy
map cc clear
map <enter> open
map "<c-\>" shell

# wallpaper
map cw setwallpaper

# bookmaks key
map gh cd ~
map gd cd ~/.dotfiles
map gc cd ~/.config
map gt cd ~/.Trash
map gp cd ~/pix
map ge cd ~/ebook
map gm cd ~/Movies/videos
map go cd ~/Downloads
map gl cd /usr/local
map gb cd /opt/homebrew
