format = """
(#4c566a)\
$username\
(bg:#DA627D fg:#9A348E)\
$directory\
(fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
(fg:#FCA17D bg:#86BBD8)\
$lua\
$python\
$nodejs\
$time\
(fg:#33658A)\
"""

add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#4c566a"
style_root = "bg:#4c566a"
format = '[ $user ]($style)'

[directory]
style = "bg:#3b4252 fg:#ffffff"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "


[git_branch]
symbol = ""
style = "bg:#88c0d0 fg:#d8dee9"
format = '[[ $symbol $branch ](bg:#88c0d0 fg:#d8dee9)]($style)'

[git_status]
style = "bg:#88c0d0 fg:#d8dee9"
format = '[[($all_status$ahead_behind )](bg:#88c0d0 fg:#d8dee9)]($style)'

[nodejs]
symbol = ""
style = "bg:#d8dee9"
format = '[[ $symbol ($version) ](bg:#d8dee9 fg:#262626)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#81a1c1"
format = '[[ ♥ $time ](bg:#81a1c1)]($style)'

[lua]
style = "bg:#d8dee9"
format = "[[  ($version) ](bg:#d8dee9 fg:#d9dee0)]($style)"

[python]
style = "bg:#d8dee9"
format = '[[ $symbol ($version) ](bg:#d8dee9 fg:#d2dee0)]($style)'

