-- GRUVBOX_MATERIAL
vim.g.gruvbox_material_background = "soft"
vim.g.gruvbox_materual_enable_italic = 1
vim.g.gruvbox_material_disable_italic_comment = 1
vim.g.gruvbox_material_enable_bold = 0
vim.g.gruvbox_material_cursor = "auto"
vim.g.gruvbox_material_current_word = "grey background"
vim.g.gruvbox_material_transparent_background = 1
vim.g.gruvbox_material_visual = "grey background"
vim.g.gruvbox_materual_menu_selection_background = "grey"
vim.g.gruvbox_material_sign_column_background = "default"
vim.g.gruvbox_material_spell_foreground = "colored"
vim.g.gruvbox_material_ui_contrast = "low"
vim.g.gruvbox_material_diagnostic_text_highlight = 1
vim.g.gruvbox_material_diagnostic_line_highlight = 1
vim.g.gruvbox_material_diagnostic_virtual_text = "colored"
vim.g.gruvbox_material_statusline_style = "original"
vim.g.gruvbox_material_palette = "mix"
vim.g.gruvbox_material_better_performance = 1
