#!/bin/sh

# EXA
TREE_IGNORE="cache|log|logs|node_modules|vendor"
alias ls="exa --group-directories-first --icons"
alias la="ls -a"
alias ll="ls --git -lah "
alias lt='ls --tree -D -L 2 -I ${TREE_IGNORE}'
alias npml="npm list --location=global --depth=0"

# HTOP
alias htop="htop --tree"

# ZSH
alias src="source ~/.config/zsh/.zshrc"
alias zshrc="$EDITOR ~/.config/zsh/.zshrc"

# GIT
alias lg="lazygit"

# BREW PINNED
alias brewlistpin="brew list --pinned"

# BREW CLEAN
alias brewclean="brew cleanup --prune=all"

# NEOVIM
alias vi="$EDITOR"

# TMUX
alias tmuxconf="$EDITOR ~/.config/tmux/tmux.conf"
alias ide="tmux split-window -h -p 35 && tmux select-pane -t 0"
alias ta='tmux attach -t'
alias tad='tmux attach -d -t'
alias ts='tmux new-session -s'
alias tl='tmux list-sessions'
alias tksv='tmux kill-server'
alias tkss='tmux kill-session -t'

# default commandline
alias cp="cp -v -i"
alias mv="mv -v -i"
alias rm="rm -v -i"
alias ln="ln -v"
alias mkdir="mkdir -p"

# system information
alias btw="neofetch"

# kitty
alias icat="kitty +kitten icat"
alias kittyconf="$EDITOR ~/.config/kitty/kitty.conf"

# python
alias pyls="ls /usr/local/share/pyenv/versions/"

# check path
alias cpath="
echo '----------------------\n'\
'PATH ⚙️\n'$PATH | tr ':' '\n' && echo '----------------------\n'\
'FPATH 🤖\n'$FPATH | tr ':' '\n' && echo '----------------------\n'\
'MANPATH 📖\n'$MANPATH | tr ':' '\n' && echo '----------------------\n'\
"

# WGET
alias wget="wget --hsts-file='$XDG_DATA_HOME/wget-hsts/.wget-hsts'"

# GITHUB
alias gh="open \`git remote -v | grep fetch | awk '{print \$2}' | sed 's/git@/http:\/\//' | sed 's/com:/com\//'\`| head -n1"

# OHMYSHELL
alias cds="~/.dotfiles/scripts/"
#
alias python="python3"
alias pip="pip3"

# kill
alias fkill='osx -k'

# free like linux
alias free="top -l 1 -s 0 | awk ' /Processes/ || /PhysMem/ || /Load Avg/{print}'"

# pipe-viewer
alias msv="pipe-viewer --player=mpv"
alias msc="pipe-viewer -n --no-video-info --player=mpvt"
