#!/bin/sh

export NVM_DIR="/opt/homebrew/opt/nvm"
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# PATH
# BREW
# (M1)    /opt/homebrew/bin /opt/homebrew/sbin
# (INTEL) /usr/local/bin /usr/local/sbin
eval "$(/opt/homebrew/bin/brew shellenv)"

# EDITOR
export EDITOR="nvim"

# TMUX
export TMUX_CONF="$XDG_CONFIG_HOME/tmux/tmux.conf"

# GIT
export GIT_CONFIG_GLOBAL="$XDG_CONFIG_HOME/git/config"

# HOMEBREW
export HOMEBREW_BREWFILE="$XDG_CONFIG_HOME/brewfile/Brewfile"

# TERMINFO
export TERMINFO="$XDG_DATA_HOME/terminfo"
export TERMINFO_DIRS="$XDG_DATA_HOME/terminfo:/usr/share/terminfo"

# NODE
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node/.node_repl_history"

# GEM
export GEM_HOME="${XDG_DATA_HOME}/gem"
export GEM_SPEC_CACHE="${XDG_CACHE_HOME}/gem"

# YABAI
export YABAI_CERT="yabai-cert"
