#!/bin/sh

# FZF_LAYOUT
export FZF_DEFAULT_OPTS="--height 50% \
  --layout=reverse \
  --border sharp \
  --inline-info \
  --margin 0,0.40% \
  "

# FZF_COLORSCHEME_NORD
export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
  --color=fg:#D8DEE9
  --color=bg:#2E3440
  --color=hl:#A3BE8C
  --color=fg+:#D8DEE9
  --color=bg+:#434C5E
  --color=hl+:#A3BE8C
  --color=pointer:#BF616A
  --color=info:#4C566A
  --color=spinner:#4C566A
  --color=header:#4C566A
  --color=prompt:#81A1C1
  --color=marker:#EBCB8B
  '

# VARIABLE
EXCLUDE_FZF=' \
  --exclude=.git \
  --exclude=.gem \
  --exclude=.cache \
  --exclude=.vscode \
  --exclude=.npm \
  --exclude=.Trash \
  --exclude=.ssh \
  --exclude=.vim \
  --exclude=.lldb \
  --exclude=.docker \
  --exclude=.viminfo \
  --exclude=.lesshst \
  --exclude=.dotfiles \
  --exclude=.DS_Store \
  --exclude=.localized \
  --exclude=.eslint_d \
  --exclude=.CFUserTextEncoding \
  --exclude=.local/lib \
  --exclude=.local/state \
  --exclude=.local/share \
  --exclude=.local/include \
  --exclude=.config/karabiner/automatic_backups \
  --exclude=.config/tmux/plugins \
  --exclude=.config/zsh/plugin \
  --exclude=node_modules \
  --exclude=Library \
  --exclude=Pictures \
  --exclude=Movies \
  --exclude=Postman \
  --exclude=Desktop \
  --exclude=Documents \
  --exclude=Music \
  --exclude=Public \
  --exclude=Applications \
  '

BAT="--preview \
  'bat \
  --style=plain \
  --color=always \
  --line-range :500 {}'\
  "

TREE="--preview \
  'tree -C {}'
  "

# FZF DEFAULT COMMAND
export FZF_DEFAULT_COMMAND="fd -H -L --strip-cwd-prefix $EXCLUDE_FZF"

# FZF COMPLETIONS
export FZF_COMPLETION_TRIGGER="~~"

# CTRL_T | files
export FZF_CTRL_T_OPTS="$BAT"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND --type f"

# CTRL_R | history
export FZF_CTRL_R_OPTS="--preview \
  'echo {}' \
  --preview-window down:3:hidden:wrap --bind ']:toggle-preview'\
  "
export FZF_CTRL_R_COMMAND=""

# ALT_C | directory
export FZF_ALT_C_OPTS="$TREE"
export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND --type d "

# REBIND ALT_C TO CTRL_P
bindkey "^P" fzf-cd-widget

# ALIAS
alias vd="cd ~ && cd \$($FZF_DEFAULT_COMMAND -d 7 --type d | fzf --prompt='👉 change directory > ' $TREE)"
alias vn="$FZF_DEFAULT_COMMAND -d 7 --type f | fzf $BAT --prompt='💻 open on editor > ' | xargs nvim"
alias dman="preview ~/Documents/ebook"

# Manpage
fman() {
  man -k . | fzf --prompt='manpage 💁 > ' --multi | awk -F "(" '{print $1}' | xargs -r man
}

# MANPAGER_BAT
export MANPAGER="sh -c 'col -bx | bat -l=man --style=plain --paging=always '"
