#!/usr/bin/env sh

source "$HOME/.config/sketchybar/color.sh"

PLUGIN_DIR="$HOME/.config/sketchybar/controller"
PLUGIN_TOUCH="$HOME/.config/sketchybar/controller/touch"
ITEM_DIR="$HOME/.config/sketchybar/view"

PADDING=4
FONT="JetBrainsMono Nerd Font Mono"

sketchybar --bar     height=28                                            \
                     blur_radius=0                                        \
                     padding_left=10                                      \
                     padding_right=16                                     \
                     color=0xff${NORD0:1}                                 \
                     position=top                                         \
                     sticky=on                                            \
                     font_smoothing=on                                    \

sketchybar --default updates=when_shown                                   \
                     drawing=on                                           \
                     icon.font="$FONT:Regular:10.0"                       \
                     label.font="$FONT:Regular:10.0"                      \
                     icon.color=0xff${NORD6:1}                            \
                     label.color=0xff${NORD6:1}                           \
                     icon.padding_left=$PADDING                           \
                     icon.padding_right=$PADDING                          \
                     label.padding_left=$PADDING                          \
                     label.padding_right=$PADDING                         \


# left
source "$ITEM_DIR/space.sh"
source "$ITEM_DIR/front_app.sh"

# right
source "$ITEM_DIR/time.sh"
source "$ITEM_DIR/cal.sh"
source "$ITEM_DIR/disk.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/airpodsbattery.sh"
source "$ITEM_DIR/sound.sh"
source "$ITEM_DIR/mic.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/mem.sh"
source "$ITEM_DIR/cpu.sh"

# initializing
sketchybar --update

echo "sketchybar configuration loaded.."
