#!/usr/bin/env sh

source "$HOME/.config/sketchybar/color.sh"

PLUGIN_DIR="$HOME/.config/sketchybar/plug"

PADDING=4
FONT="JetBrainsMono Nerd Font Mono"

sketchybar --bar     height=28                                            \
                     blur_radius=0                                        \
                     position=top                                         \
                     sticky=on                                            \
                     padding_left=10                                      \
                     padding_right=10                                     \
                     color=0xff${NORD0:1}

sketchybar --default updates=when_shown                                   \
                     drawing=on                                           \
                     icon.font="$FONT:Bold:12.0"                          \
                     icon.color=0xffffffff                                \
                     icon.padding_left=$PADDING                           \
                     icon.padding_right=$PADDING                          \
                     label.font="$FONT:SemiBold:11.0"                     \
                     label.color=0xffffffff                               \
                     label.padding_left=$PADDING                          \
                     label.padding_right=$PADDING

SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")

for i in "${!SPACE_ICONS[@]}"
do
  sid=$(($i+1))
  sketchybar --add space space.$sid left                                 \
             --set space.$sid associated_space=$sid                      \
                              icon=${SPACE_ICONS[i]}                     \
                              icon.padding_left=8                        \
                              icon.padding_right=8                       \
                              background.padding_left=4                  \
                              background.padding_right=4                 \
                              background.corner_radius=4                 \
                              background.height=22                       \
                              background.color=0x44ffffff                \
                              background.drawing=off                     \
                              label.drawing=off                          \
                              script="$PLUGIN_DIR/space.sh"              \
                              click_script="yabai -m space --focus $sid"
done

sketchybar --add item space_separator left                              \
           --set space_separator icon=                                 \
                                 background.padding_left=0              \
                                 background.padding_right=4             \
                                 label.drawing=off                      \
                                                                        \
           --add item front_app  left                                   \
           --set front_app       script="$PLUGIN_DIR/front_app.sh"      \
                                 icon.drawing=off                       \
           --subscribe front_app front_app_switched

sketchybar --add item clock right                                       \
           --set clock   update_freq=10                                 \
                         script="$PLUGIN_DIR/clock.sh"                  \
                                                                        \
           --add item battery right                                     \
           --set battery script="$PLUGIN_DIR/battery.sh"                \
                         update_freq=10                                 \
           --subscribe battery system_woke

sketchybar --update

echo "sketchybar configuration loaded.."
