#!/usr/bin/env sh

source "$HOME/.config/sketchybar/color.sh"

PLUGIN_DIR="$HOME/.config/sketchybar/plug"
ITEM_DIR="$HOME/.config/sketchybar/items"

PADDING=4
FONT="JetBrainsMono Nerd Font Mono"

sketchybar --bar     height=26                                            \
                     blur_radius=0                                        \
                     position=top                                         \
                     sticky=on                                            \
                     padding_left=10                                      \
                     padding_right=16                                     \
                     color=0xff${NORD0:1}

sketchybar --default updates=when_shown                                   \
                     drawing=on                                           \
                     icon.font="$FONT:Bold:12.0"                          \
                     label.font="$FONT:SemiBold:11.0"                     \
                     icon.color=0xff${NORD6:1}                            \
                     label.color=0xff${NORD6:1}                           \
                     icon.padding_left=$PADDING                           \
                     icon.padding_right=$PADDING                          \
                     label.padding_left=$PADDING                          \
                     label.padding_right=$PADDING

# left
source "$ITEM_DIR/space.sh"
source "$ITEM_DIR/front_app.sh"

# right
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/memory.sh"

# initializing
sketchybar --update

echo "sketchybar configuration loaded.."
