#!/usr/local/bin/bash

set -e

walldir="$HOME/pix/save"

tagoptions="#4\n#nature\n#minimalism\n#cyberpunk\n#digital art\n#science fiction"
if [ -z "$1" ]; then
	query="$(echo -e $tagoptions | fzf --prompt="search wallhaven > ")"
else
	query="${*:1}"
fi

sortingopts="date_added\nrelevance\nrandom\nviews\nfavorites\ntoplist"
sorting=$(echo -e $sortingopts | fzf --prompt="sorting > ")

pageslength="1\n2\n3\n4\n5"
pages=$(echo -e $pageslength | fzf --prompt="pages > ")

query=$(sed 's/#//g' <<<$query)
query=$(sed 's/ /+/g' <<<$query)
echo $query

for i in $(seq 1 $pages); do
	curl https://wallhaven.cc/api/v1/search\?atleast\=1920x1080\&ratios\=16x9\&sorting\=$sorting\&q\=$query\&page\=$i >tmp.txt
	page=$(cat tmp.txt | jq '.' | grep -Eoh "https:\/\/w\.wallhaven.cc\/full\/.*(jpg|png)\b")
	wget -nc -P $walldir $page --no-check-certificate
done

rm tmp.txt

if [ "$TERM" == "tmux-256color" ]; then
	open -a qview $(fd . $walldir -t f | tail -1)
else
	lf "$(fd . $walldir -t f | tail -1)"
fi
