#!/bin/bash

set -e

__open_current() {
	open "$@"
}

__gjson() {
	curl "${@}" | jq . | bat -l=json
}

__kill() {
	kill -9 "$(ps -ax -o pid,%cpu,%mem,comm | sort -b -k3 -r | fzf --multi --prompt='kill process > ' | awk '{print $1}')" 2>/dev/null
}

__help() {
	cat <<-_EOF_
		OSX Utils 💻

		pattern osx [cmd | path] :
		-g --gjson curl | preview json
		-p --path open specified path
		-k --kill search and kill background process
		-h --help help information
	_EOF_
}

if [ "$1" = "-p" ] || [ "$1" = "--path" ]; then
	__open_current "$2"
elif [ "$1" = "-g" ] || [ "$1" = "--gjson" ]; then
	__gjson "${@:2}"
	exit
elif
	[ "$1" = "-k" ] || [ "$1" = "--kill" ]
then
	__kill
elif [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
	__help
	exit
elif [ -n "$1" ]; then
	echo "osx not found 🙅"
	echo "osx -help for information 💁"
	exit
else
	echo "osx not found 🙅"
	echo "osx -help for information 💁"
fi
