#!/usr/local/bin/bash

set -e

__open_current() {
	open "$@"
}

__kill() {
	kill -9 $(ps -ax -o pid,comm | sort | fzf -m | awk '{print $1}' | tr '\n' ' ') 2>/dev/null
}

__displayopts() {
	open -b com.apple.systempreferences /System/Library/PreferencePanes/Displays.prefPane
}

__help() {
	cat <<-_EOF_
		OSX Utils 💻

		pattern osx [cmd | path] :
		-p --path open specified path
		-k --kill search and kill background process
		-d --display open system preferences display
		-h --help help information
	_EOF_
}

if [ "$1" = "-p" ] || [ "$1" = "--path" ]; then
	__open_current "$2"
elif [ "$1" = "-k" ] || [ "$1" = "--kill" ]; then
	__kill
elif [ "$1" = "-d" ] || [ "$1" = "--display" ]; then
	__displayopts
elif [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
	__help
	exit
elif [ -n "$1" ]; then
	echo "osx not found 🙅"
	echo "osx --help for information 💁"
	exit
else
	echo "osx not found 🙅"
	echo "osx --help for information 💁"
fi
