#!/bin/bash

set -e

n="nnn -d -P v"
ebook_paths="$HOME/ebook"

__help() {
	cat <<-_EOF_
		Preview Utils 🐣

		preview [cmd | path] :
		-i --image open image
		-e --ebook open ebook [add config path]
		-m --man open manpage

		Requirement :
		fzf:       fuzzy finder [https://github.com/junegunn/fzf]
		fd:        find replacement [https://github.com/sharkdp/fd]
		zathura:   pdf [https://github.com/zegervdv/homebrew-zathura]
	_EOF_
}

if [ "$1" = "-i" ] || [ "$1" = "--image" ]; then
	if [ "$TERM" = "tmux-256color" ]; then
		$n $(fd . -L -t f --exclude=Library | grep -E '.*(jpg|png)' | sort -r | awk '{print $1}' | fzf --multi --prompt='👉 open image > ')
	else
		$n $(fd . -L -t f --exclude=Library | grep -E '.*(jpg|png)' | sort -r -u | fzf --multi --prompt='👉 open image > ')
	fi
elif [ "$1" = "-e" ] || [ "$1" = "--ebook" ]; then
	fd . "$ebook_paths" --type f | fzf --multi --prompt="👉 open book > " | xargs zathura --fork 2>/dev/null
	exit
elif [ "$1" = "-m" ] || [ "$1" = "--man" ]; then
	man -k . | fzf --multi --prompt='👉 manpage > ' | awk -F "(" '{print $1}' | xargs -r man
elif [ "$1" = "-h" ]; then
	__help
	exit
elif [ -n "$1" ]; then
	echo "preview not found 🙅"
	echo "preview -help for information 💁"
	exit
else
	echo "preview not found 🙅"
	echo "preview -help for information 💁"
fi
