#!/bin/bash

set -e

ebooks_path="$HOME/ebook"
movies_path="$HOME/Movies/videos"

__help() {
	cat <<-_EOF_
		Preview Utils 🐣

		preview [cmd | path] :
		-i --image open image
		-e --ebook open ebook [add config path]
		-m --man open manpage

		Requirement :
		fzf:     fuzzy finder [https://github.com/junegunn/fzf]
		fd:      find replacement [https://github.com/sharkdp/fd]
		zathura: pdf [https://github.com/zegervdv/homebrew-zathura]
		qview:   for open previewer [brew install qview]
	_EOF_
}

if [ "$1" = "-i" ] || [ "$1" = "--image" ]; then
	filter=$(fd . -L -t f --exclude=Library | grep -E '.*(jpg|png)' | sort -r | fzf --prompt='👉 open image > ')
	open -a qview $filter
elif [ "$1" = "-v" ] || [ "$1" = "--video" ]; then
	filter=$(fd . $movies_path -t f | grep -E '.*(mp4)' | sort -u | fzf -m --prompt='👉 open video > ')
	mpv $filter
elif [ "$1" = "-e" ] || [ "$1" = "--ebook" ]; then
	fd . "$ebooks_path" --type f | fzf -m --prompt="👉 open ebook > " | xargs zathura --fork 2>/dev/null
	exit
elif [ "$1" = "-m" ] || [ "$1" = "--man" ]; then
	man -k . | sort | uniq | fzf --prompt='👉 open manpage > ' | awk -F "(" '{print $1}' | xargs -r man
elif [ "$1" = "-h" ]; then
	__help
	exit
elif [ -n "$1" ]; then
	echo "preview not found 🙅"
	echo "preview -help for information 💁"
	exit
else
	echo "preview not found 🙅"
	echo "preview -help for information 💁"
fi
