#!/bin/bash

set -e

youtube="https://youtube.com/results?search_query="
piped="https://piped.kavin.rocks/results?search_query="
music="https://listen.whatever.social/search/"
google="https://www.google.com/search?q="
reddit="https://www.reddit.com/search/?q="
stackoverflow="https://stackoverflow.com/search?q="
github="https://github.com/search?q="
udemy="https://www.udemy.com/courses/search"

search() {
	open -a Brave\ Browser "$*"
}

youtube() {
	search "$youtube$*"
}

piped() {
	search "$piped$*"
}

music() {
	search "$music$*"
}

google() {
	search "$google$*"
}

stackoverflow() {
	search "$stackoverflow$*"
}

reddit() {
	search "$reddit$*"
}

github() {
	search "$github$*&type=repositories"
}

udemy() {
	search "$udemy/?price=price-free&q=$*&sort=relevance&src=ukw"
}

help() {
	cat <<-_EOF_
		Browser Search Utils 🌏

		search [command|args] :
			-gt --github search repositories
			-rd --reddit search content
			-so --overflow search content
			-go --duckduckgo search content
			-yt --youtube search content
			-pi --piped youtube alternative less distraction
			-ps --music youtube music alternative
			-h  --help for help information

		Requirement :
		browser: by default brave
	_EOF_
}

if [ "$1" == "-gt" ] || [ "$1" == "--github" ]; then
	github "${@:2}"
	exit
elif [ "$1" == "-go" ] || [ "$1" == "--google" ]; then
	google "${@:2}"
	exit
elif [ "$1" == "-pi" ] || [ "$1" == "--piped" ]; then
	piped "${@:2}"
	exit
elif [ "$1" == "-yt" ] || [ "$1" == "--youtube" ]; then
	youtube "${@:2}"
	exit
elif [ "$1" == "-ps" ] || [ "$1" == "--music" ]; then
	music "${@:2}"
	exit
elif [ "$1" == "-rd" ] || [ "$1" == "--reddit" ]; then
	reddit "${@:2}"
	exit
elif [ "$1" == "-so" ] || [ "$1" == "--overflow" ]; then
	stackoverflow "${@:2}"
	exit
elif [ "$1" == "-ud" ] || [ "$1" == "--udemy" ]; then
	udemy "${@:2}"
	exit
elif [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
	help "${@:2}"
	exit
elif [ -n "$1" ]; then
	echo "search not found 🙅"
	echo "search -help for information 💁"
	exit
else
	echo "search not found 🙅"
	echo "search -help for information 💁"
fi
