#!/bin/bash

set -e

search() {
	open -a Brave\ Browser "$*"
}

youtube() {
	youtube="https://youtube.com/results?search_query="
	search "$youtube$*"
}

google() {
	google="https://www.google.com/search?q="
	search "$google$*"
}

stackoverflow() {
	stackoverflow="https://stackoverflow.com/search?q="
	search "$stackoverflow$*"
}

reddit() {
	reddit="https://www.reddit.com/search/?q="
	search "$reddit$*"
}

github() {
	github="https://github.com/search?q="
	search "$github$*&type=repositories"
}

devto() {
	devto="https://dev.to/search?q="
	search "$devto$*"
}

udemy() {
	udemy="https://www.udemy.com/courses/search"
	search "$udemy/?price=price-free&q=$*&sort=relevance&src=ukw"
}

help() {
	cat <<-_EOF_
		Browser Search Utils 🌏

		search [command|args] :
			-gt --github search repositories
			-rd --reddit search content
			-so --overflow search content
			-go --duckduckgo search content
			-yt --youtube search content
			-ud --udemy search courses
			-h  --help for help information

		Requirement :
		browser: by default brave
	_EOF_
}

if [ "$1" == "-gt" ] || [ "$1" == "--github" ]; then
	github "${@:2}"
	exit
elif [ "$1" == "-go" ] || [ "$1" == "--google" ]; then
	google "${@:2}"
	exit
elif [ "$1" == "-yt" ] || [ "$1" == "--youtube" ]; then
	youtube "${@:2}"
	exit
elif [ "$1" == "-rd" ] || [ "$1" == "--reddit" ]; then
	reddit "${@:2}"
	exit
elif [ "$1" == "-so" ] || [ "$1" == "--overflow" ]; then
	stackoverflow "${@:2}"
	exit
elif [ "$1" == "-ud" ] || [ "$1" == "--udemy" ]; then
	udemy "${@:2}"
	exit
elif [ "$1" == "-dt" ] || [ "$1" == "--devto" ]; then
	devto "${@:2}"
	exit
elif [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
	help "${@:2}"
	exit
elif [ -n "$1" ]; then
	echo "search not found 🙅"
	echo "search --help for information 💁"
	exit
else
	echo "search not found 🙅"
	echo "search --help for information 💁"
fi
