#!/usr/local/bin/bash

connect_ssh() {
	ssh_ls=$(cat $(find ~/.config/ssh_servers/** | sort | awk '{print $1}') | fzf --prompt="select ssh server > ")
	cmd="$(ssh "$ssh_ls")"

	if [ "$ssh_ls" == "" ]; then
		exit
	else
		$cmd 2>/dev/null
	fi
}

connect_ssh
