#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config                                 \
     mouse_follows_focus          off           \
     focus_follows_mouse          off           \
     window_origin_display        default       \
     window_placement             second_child  \
     window_topmost               off           \
     window_shadow                off           \
     window_opacity               off           \
     window_border                on            \
     window_animation_duration    0.35          \
     window_opacity_duration      0.35          \
     normal_window_opacity        0.90          \
     active_window_opacity        1.0           \
     window_border_width          6             \
     split_ratio                  0.50          \
     split_type                   auto          \
     active_window_border_color   0xffD4D4D4    \
     normal_window_border_color   0xff949292    \
     insert_feedback_color        0xff949292    \
     auto_balance                 off           \
     mouse_modifier               fn            \
     mouse_action1                move          \
     mouse_action2                resize        \
     mouse_drop_action            swap          \

# yabai 5.0.x support this opts but broken in border
# yabai -m config                                 \
#      window_border_hidpi          on            \
#      window_border_blur           on            \
#      window_border_radius         0             \

# general space settings
yabai -m config                       \
     layout                       bsp \
     top_padding                  40  \
     bottom_padding               15  \
     left_padding                 15  \
     right_padding                15  \
     window_gap                   8   \

yabai -m rule -add app="^System Preferences$" manage=off

echo "yabai configuration loaded.."
