#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)

# Loadscript
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Settings
yabai -m config																							\
	mouse_follows_focus off																		\
	focus_follows_mouse off																		\
	window_origin_display default															\
	window_placement second_child 														\
	window_shadow float																				\
	window_topmost off																				\
	window_opacity on																					\
	window_border on																					\
	window_animation_duration 0.35														\
	window_opacity_duration 0.35															\
	normal_window_opacity 0.90																\
	active_window_opacity 0.95																\
	window_border_width 4																			\
	split_ratio 0.50																					\
	split_type auto																						\
	active_window_border_color 0xffB48EAD											\
	normal_window_border_color 0xffb8abb5 										\
	insert_feedback_color 0xff949292													\
	auto_balance off																					\
	mouse_modifier fn																					\
	mouse_action1 move																				\
	mouse_action2 resize																			\
	mouse_drop_action swap

yabai -m config													\
	window_border_hidpi on								\
	window_border_blur on									\
	window_border_radius 0

# Padding
yabai -m config													\
	layout bsp														\
	top_padding 40												\
	bottom_padding 15											\
	left_padding 15												\
	right_padding 15											\
	window_gap 8

# MacOS
yabai -m rule --add label="About This Mac" app="System Information" manage=off
yabai -m rule --add label="System Settings" app="^System Settings$" title=".*" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Finder" app="^Finder" manage=off
yabai -m rule --add label="Simulator" app="^Simulator" manage=off
yabai -m rule --add label="Disk Utility" app="^Disk Utility" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor" manage=off
yabai -m rule --add label="Preview" app="^Preview" manage=off

# External App
yabai -m rule --add label="karabiner-elements" app="^Karabiner-Elements" manage=off
yabai -m rule --add label="karabiner-event-viewer" app="^Karabiner-EventViewer" manage=off
yabai -m rule --add label="alt-tab" app="^AltTab" manage=off
yabai -m rule --add label="mvp" app="^mpv" manage=off

yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

# custom space window
yabai -m rule --add app="^kitty$" space=1
yabai -m rule --add app="^Brave Browser$" space=2
yabai -m rule --add app="^(mpv)$" space=3
yabai -m rule --add app="^(Whatsapp|Discord)$" space=4
yabai -m rule --add app="^Mail$" space=5
yabai -m rule --add app="^(Messages|FaceTime)$" space=6

# yabai -m signal --add event=space_changed \

echo "yabai configuration loaded.."
